# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('style', models.CharField(max_length=80, verbose_name='Estilo musical')),
                ('instrument', models.CharField(max_length=80, verbose_name='Instrumento')),
                ('state', models.CharField(max_length=80, verbose_name='Estado')),
                ('adress', models.CharField(max_length=100, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Facebook')),
                ('face', models.CharField(blank=True, max_length=20, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=20, null=True, verbose_name='Twitter')),
                ('insta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Instagram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
