# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('cover', models.FileField(blank=True, null=True, upload_to='cover/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone'),
        ),
    ]
