# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170705_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='video',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Video'),
        ),
    ]
